apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: caas-offsite-01
  namespace: default
spec:
  parameters:
    id: caas-offsite-01
    region: eu-central-1
    version: "1.27"
    iam:
      roleArn: arn:aws:iam::609897127049:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: t3.small
    gitops:
      url: https://github.com/haarchri/gitops-offsite
      path: infrastructure/caas-offsite-01
  writeConnectionSecretToRef:
    name: caas-offsite-01-kubeconfig
